In [1]:
# Lets calculate didvidend yield
# Dividend Yield = Annual Dividend / Current Stock Price

dividends = [1, 1.5, 1.75, 0.75, 1.25]
stock_prices = [50, 55, 62, 47, 84]

In [2]:
# Dividend Yield = Annual Dividend / Current Stock Price
# can not do dividends/stock_prices
import numpy as np

In [3]:
# lets convert lists into numpy arrays
# If you use different types NumPy converts everything to string
np_dividends = np.array(dividends)
np_stock_prices = np.array(stock_prices)
np_stock_prices

array([50, 55, 62, 47, 84])

In [4]:
# now we can easy perform calculations
dividend_yield = np_dividends/np_stock_prices*100
dividend_yield

array([ 2.        ,  2.72727273,  2.82258065,  1.59574468,  1.48809524])

In [5]:
# NumPy behaves differently than Python

a = [1,2,3]
b = [4,5,6]
c = a + b
c

[1, 2, 3, 4, 5, 6]

In [6]:
# NumPy adds items
b = np.array(b)
c = a + b
c

array([5, 7, 9])

In [8]:
dividend_yield[1]
dividend_yield

array([ 2.        ,  2.72727273,  2.82258065,  1.59574468,  1.48809524])

In [9]:
# values greater than 2.72
dividend_yield > 2.72

array([False,  True,  True, False, False], dtype=bool)

In [10]:
# or you could get the actual values
dividend_yield[dividend_yield > 2.72]

array([ 2.72727273,  2.82258065])

In [11]:
# we can create 2d array from a regular python list of lists
np_2d = np.array([[1, 1.5, 1.75, 0.75, 1.25],[50, 55, 62, 47, 84]])
np_2d

array([[  1.  ,   1.5 ,   1.75,   0.75,   1.25],
       [ 50.  ,  55.  ,  62.  ,  47.  ,  84.  ]])

In [12]:
# we got rectangular data structure
# lets see how many rows and colums using shape
np_2d.shape

(2, 5)

In [13]:
# with a 2d array we can do indexing 
np_2d[1]

array([ 50.,  55.,  62.,  47.,  84.])

In [14]:
np_2d.resize((5,2))
np_2d

array([[  1.  ,   1.5 ],
       [  1.75,   0.75],
       [  1.25,  50.  ],
       [ 55.  ,  62.  ],
       [ 47.  ,  84.  ]])

In [15]:
np_2d[1][1]

0.75

In [16]:
# or you could subsetting
# [row,column]
np_2d[1,1]

0.75

In [17]:
# or we could get entire second row
np_2d[1,:]

array([ 1.75,  0.75])

In [18]:

np_2d[1:3]

array([[  1.75,   0.75],
       [  1.25,  50.  ]])

In [19]:
np_2d.resize((2,5))
np_2d

array([[  1.  ,   1.5 ,   1.75,   0.75,   1.25],
       [ 50.  ,  55.  ,  62.  ,  47.  ,  84.  ]])

In [20]:
# Similarly we can use mean and median functions for the whole row 
avarage_stock_price = np.mean(np_2d[1,:])
avarage_stock_price

59.600000000000001

In [21]:
#standard diviation
sd = np.std(np_2d[1,:])
sd

13.215142829345433

In [22]:
#sum
s = np.sum(np_2d[1,:])
s

298.0

In [23]:
# generate data
# (distribution mean, standard dev., number of samples)

prices = np.round(np.random.normal(50, 0.20, 10), 2)
prices

array([ 49.6 ,  49.86,  49.87,  49.55,  50.02,  49.95,  50.32,  49.95,
        50.42,  50.02])

In [24]:
dividends = np.round(np.random.normal(1.25, 0.20, 10), 2)
dividends

array([ 1.43,  0.98,  1.35,  1.43,  0.93,  1.55,  1.22,  1.35,  1.05,  0.99])

In [25]:
# create two columns
portfolio = np.column_stack((prices, dividends))
portfolio

array([[ 49.6 ,   1.43],
       [ 49.86,   0.98],
       [ 49.87,   1.35],
       [ 49.55,   1.43],
       [ 50.02,   0.93],
       [ 49.95,   1.55],
       [ 50.32,   1.22],
       [ 49.95,   1.35],
       [ 50.42,   1.05],
       [ 50.02,   0.99]])

In [26]:
# lets check median stock price
m = np.median(portfolio[:,0])
m

49.950000000000003